 export const sortData = [
    {
      heading: "Select Diet",
      id: "dietSort",
      options: [
        "Vegan",
        "Vegeterian",
        "Ketogenic",
        "Pescetarian",
        "Gluten Free",
        "Primal",
        "Paleo",
        "Whole30",
        "Lacto-Vegeterian",
        "Low FODMAP",
      ],
    },
    {
      heading: "Select cusine",
      id: "cusineSort",
      options: [
        "Asian",
        "American",
        "British",
        "Chinese",
        "European",
        "Italian",
        "Indian",
        "Japanese",
        "Korean",
        "Mexican",
      ],
    },
    {
      heading: "Select Meal",
      id: "mealSort",
      options: [
        "Main course",
        "Side Dish",
        "Dessert",
        "Salad",
        "Breakfast",
        "Soup",
        "Beverage",
        "Marinade",
        "Snack",
        "drink",
      ],
    },
  ];
